version: '3.7'

services:
  weblab-nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /home/bogdan/projects/client/build:/var/www/frontend
    network_mode: host
    restart: always
