version: '3.7'

services:
  weblab-nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /home/pi/mcu-and-fpga-remote-lab-frontend/build:/var/www/frontend
      - ./cert:/etc/nginx/ssl
    network_mode: host
    restart: always
